spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

mybatis:
  mapper-locations: mapper/*.xml
  type-aliases-package: com.springboot.mybatis.model.dto # parameterType? resultType? ??path